### ISSUE TITLE
Error importing orbit.extension - No module named 'omni.physics'

### ISSUE THREAD

**Issue by giulioturrisi** [isaac-orbit/orbit.ext_template#13]
Hi all, 

I followed the instructions in the README, and linked orbit with my orbit.my_extension folder using ln -s. When i try to import it, as

import orbit.my.extension

I obtained the following error:
 
ModuleNotFoundError: No module named 'omni.physics'

I'm using conda, and I'm able to use orbit normally. Do you have any suggestion to solve it?

Thanks,
Giulio

**Comment by giulioturrisi** [comment]
The error goes away after i launch the following:

# launch omniverse app
app_launcher = AppLauncher(args_cli)

plus all before this line
https://github.com/isaac-orbit/orbit.ext_template/blob/a9486f792da7138aba3776f36673aa30f3957492/scripts/rsl_rl/play.py#L31

**Comment by nburger-bdai** [comment]
Hi Giulio,

First off, sorry about the late response. And yess, exactly! The `AppLauncher` class is responsible for launching the simulation and extensions. Your `omni.physics` module is one of those extensions, which is why you can only access it after initializing the `AppLauncher`.

Thank you for your feedback, I will be updating the `Usage -> Python Package` of the `README.md` to be more clear.

Cheers, Nico

**Comment by garylvov** [comment]
Hi All,

Maybe [/orbit/ext_template/__init__.py](https://github.com/isaac-orbit/orbit.ext_template/blob/main/orbit/ext_template/__init__.py) could be modified to check an environment variable before attempting to register the gym environments. Something like 

```
from os import getenv

if str(getenv('REGISTER_GYM_ENVS')) == '1':
    from .tasks import * # register gym environments. 
```

That way, if you want to import something from the extension python package, you can import it as is currently in the readme without first creating an ```AppLauncher``` or the ```omni.physics``` issue . I found this to be useful for importing utility methods I wanted to include in the extension python package without first creating the ```AppLauncher``` .

Then, if you want to register the gym environment, you can easily do 
```
import os
os.environ['REGISTER_GYM_ENVS'] = "1"
import orbit.ext_template
```

(As @giulioturrisi mentioned this would require creating the app launcher first.)

If this is of any interest I'd be happy to create a PR.

Best,
Gary

**Comment by nburger-bdai** [comment]
Hey Gary,

This approach is nice to have for debugging, however, I think it would not cover the general layout of this template. The idea of this template is to have an already existing task (e.g. `AnymalDRoughEnvCfg`), which requires the `tasks` module to be imported. Otherwise the environments wouldn't be registered. I see how in the current README, the python package use case is confusing, which is why we'll get rid of this entirely in this PR.

Thank you for the inputs! I hope we can make this template as user-friendly as possible :)

Cheers, Nico
